### ISSUE TITLE
[Tracking] Regenerating completions for PRs/merges

### ISSUE THREAD

**Issue by LRitzdorf** [l-zeuch/yagpdb.vim#28] opened 2022-03-01 23:20 UTC
#24 introduced `nvim-cmp`-compatible, Lua-based completion support. This is a great feature, though it comes with a few catches for our workflow.

We've opted to commit the generated completions as we go (though end users, and developers, can always regenerate them with `make generate`). However, this means we need to ensure they're up to date, especially when PRs are merged or direct commits to master are made. This sounds like an ideal use case for GitHub Actions, and it nearly is. However, things get messy when our Generate workflow makes updates and pushes a new commit to the relevant PR branch.

We run tests and linter checks on PRs and pushes to master, so these checks should also be run on any new commits that the Generate workflow adds. In fact, in order for auto-merging to work in the GitHub UI, a PR's most recent commit *must* pass these checks. However, to prevent recursive loops, GitHub does not trigger Actions workflows on commits that are pushed by other workflows. This means that, if the most recent commit on a PR is one that causes completions to be rengenerated, the workflow will push a new commit to include those new completions. This *new* most recent commit will then be one on which our checks do not run, and auto-merging will not be available.

Ideally, there would be some way to tell GitHub, "hey, run this workflow first, and if it creates a new commit, run our other checks on that, since it's newer." This doesn't appear to be an option at the moment, so we'll have to find a workaround. The simplest is to have us, the developers, ensure that we've regenerated sources before merging anything, but as a manual task, this is inconvenient and prone to being missed during the flurry of finalizing a PR.

Please feel free to add comments below regarding this issue and any potential solutions you might have.
This issue exists primarily for documentation purposes, and will be closed with a PR that resolves this issue, one way or another.

**Comment by LRitzdorf** [comment] 2022-03-01 23:27
If nothing else, we could use https://github.com/actions/labeler to mark PRs that require completion regeneration, making them harder to miss if we end up doing things manually

**Comment by l-zeuch** [comment] 2022-03-01 23:45
As it stands, the branch protection rules no longer require status checks to pass for commits to appear on master, as well as no longer mandating commit signatures, thus the workflow can run as intended. However I'd like to have that changed back, if possible, this is merely a temporary solution. ~~because I am impatient~~

Labeler sounds like a great approach at this and as a reminder to regenerate completion sources if/as necessary. Currently the entire workflow kind of feels like a mess to me, but that might just be me and take a day or two to accustom. Let me know what you think with regards to that.

On that note: I've seen a lot of great projects work well with the workflow involved with labelling PRs and issues, so I'm positive this will work for us well, too. Of course, manual regeneration is kind of tiresome at times but really, we only need to generate those once, right before merging. In general the syntax files should rarely change, and only if new functions are added to YAGPDB.

I've been initially thinking about pre- or post-commit hooks, but as it seems and you pointed out in private conversations, those don't really seem to get cloned over, unless we've been missing something here. I'll do some research in that direction.

**Comment by l-zeuch** [comment] 2022-05-22 08:29
Closed in https://github.com/l-zeuch/yagpdb.vim/commit/1e6afae82b3e08a96a70f0985e7ae03046463d70 via #42.

**Closed by l-zeuch** 2022-05-22 08:29 UTC
Labels: type/enhancement, area/completion, meta
